In [1]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
var=np.array([1,2,3,4,5])
print(var)
print(type(var))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# checking numpy version

In [4]:
import numpy as np
print(np.__version__)

1.21.5


# to find time of particular operation

In [8]:
%timeit np.arange(1,9)**4

1.46 µs ± 46.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# creating of numpy array

In [9]:
import numpy as np
var=np.array([1,2,3])
print(var)

[1 2 3]


# to convert list into numpy array

In [10]:
import numpy as np
x=[1,2,3,4]
print(x)
print(type(x))
y=np.array(x)
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
#if user want to enter the value
l=[]
for i in range(1,5):
    var1=int(input("enter value :"))
    l.append(var1)
print(l)

enter value :12
enter value :14
enter value :15
enter value :16
[12, 14, 15, 16]


# 0-D arrays

In [12]:
var=np.array(42)
print(var)
print(type(var))

42
<class 'numpy.ndarray'>


# 1-D arrays

In [13]:
var=np.array([42])
print(var)
print(type(var))

[42]
<class 'numpy.ndarray'>


# 2-D arrays

In [18]:
var1=np.array([[12,24]])
var=np.array([[12,24],[36,48]])
print(var)
print()
print(var1)
print(type(var1))

[[12 24]
 [36 48]]

[[12 24]]
<class 'numpy.ndarray'>


# 3-D arrays

In [19]:
var2=np.array([[[1,2,3],[4,5,6]]])
print(var2)
print(type(var2))

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


# check number of dimensions

In [20]:
#to check number of dimensions use ndim
a=np.array(77)
b=np.array([12])
c=np.array([[14]])
d=np.array([[[99]]])
e=np.array([[[[[[[[[1999]]]]]]]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


0
1
2
3
9


# higher dimension array

In [23]:
#for higher dimension array use ndmin
import numpy as np
var=np.array([1,2,3,4,5],ndmin=30)
print(var)
print("no of dimensions :",var.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
no of dimensions : 30


# special numpy array

# array filled with zero

In [26]:
#for arrays filled with zeros()
import numpy as np
arzero=np.zeros(4)
print(arzero)

[0. 0. 0. 0.]


# arrays filled with ones

In [27]:
#for arrays filled with ones()
import numpy as np
arone=np.ones(4)
print(arone)

[1. 1. 1. 1.]


# create empty arrays

In [28]:
#for arrays filled with empty use empty()
import numpy as np
arempty=np.empty(6)
print(arempty)

[0. 0. 0. 0. 0. 0.]


# an array with range of elements

In [30]:
arrange=np.arange(4)
print(arrange)
arrange1=np.arange(1,10)
print(arrange1)

[0 1 2 3]
[1 2 3 4 5 6 7 8 9]


# array diagonal elements

In [31]:
ardiagonal=np.eye(3)
print(ardiagonal)
ardia=np.eye(3,10)
print(ardia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


# create array using special interval

In [34]:
#use linspace using special interval
ar_lin=np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# create numpy arrays using random numbers

In [39]:
#1)rand()- used to generate random values between 0 to 1
import numpy as np
var=np.random.rand(3,1)# here 3 represents row and 1 represents columns
print(var)

[[0.60024125]
 [0.95008228]
 [0.26106312]]


In [41]:
#2)randn() - used to generate random value to 0,it can be +ve,-ve,zero
import numpy as np
var1=np.random.randn(5)
print(var1)

[ 0.81342286  0.46742435  1.26196317 -1.79881509  1.39592163]


In [44]:
#3)ranf() - the function for doing sample in numpy . [0.0,1.0) #here 0.0 is included 1.0 is  not included
import numpy as np
var2=np.random.ranf(6)
print(var2)


[0.58992851 0.80854232 0.06873344 0.01500715 0.62406794 0.67639616]


In [47]:
#4)randint-used to generate random numbers between given range
var=np.random.randint(5,20,5)
print(var)

[ 9 12  6 13 18]


# datatypes in numpy array

In [54]:
#to find datatype use dtype
import numpy as np
var=np.array([1,2,3,4,5])
print("datatype :",var.dtype)
var1=np.array([1.0,2.0,3.0,4.0])
print("datatype :",var1.dtype)
var2=np.array(["A","B","C"])
print("datatype :",var2.dtype)
var3=np.array(["A","E","I",1,2,3,4])
print("datatype :",var3.dtype)
var4=np.array(["a","e","i",1,2,3,4,1.0,2.0,3.0])
print("datatype :",var4.dtype)


datatype : int32
datatype : float64
datatype : <U1
datatype : <U11
datatype : <U32


# convert 1 array datatype into other datatype

In [56]:
x=np.array([1,2,3,4,5])
print(x)
print("datatype :",x.dtype)
print()
#to convert int32 to int 8
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x)
print("datatype :",x.dtype)

[1 2 3 4 5]
datatype : int32

[1 2 3 4 5]
datatype : int8


In [57]:
#to convert int to float
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
x1=np.array([1,2,3,4,5],dtype="f")
print(x1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]


In [59]:
#using datatype as function convert int to float
x2=np.array([1,2,3,4])
new=np.float32(x2)
print("Datatype :",x2.dtype)
print(x2)
print("Datatype :",new.dtype)
print(new)

Datatype : int32
[1 2 3 4]
Datatype : float32
[1. 2. 3. 4.]


# directly convertion for 1 datatype to other 

In [60]:
x2=np.array([1,2,3,4,5])
new1=x2.astype(float)
print(x2)
print(type(x2))
print(new1)
print(type(new1))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


# shape

In [64]:
#use shape()
var=np.array([[1,2],[1,2]])
print(var)
print(var.shape)
print()
var1=np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print(var1.shape)

[[1 2]
 [1 2]]
(2, 2)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [65]:
#for multidimensional array
var1=np.array([1,2,3,4],ndmin=6)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[[[1 2 3 4]]]]]]
6

(1, 1, 1, 1, 1, 4)


# Reshape

In [70]:
#changing shape of numpy array
#reshape(no of rows,no of columns)


# reshape of 1d to 2d array

In [74]:
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print()
new=var.reshape(4,3)
print(new)
print()
new1=var.reshape(3,4)
print(new1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# reshape of 1d to 3d array

In [77]:
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print()
#1d to 3d
new=var.reshape(2,3,2)
print(new)
print()
# 1d to 2d
new1=var.reshape(3,2,2)
print(new1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# flattering an array

In [80]:
#converting multidimensional array into 1 d array
import numpy as np
var=np.array([[[1,2,3],[4,5,6]]])
print(var)
print()
new=var.reshape(-1)
print(new)
print()
var1=np.array([1,2,3,4,5],ndmin=31)
print(var1)
print()
new1=var1.reshape(-1)
print(new1)

[[[1 2 3]
  [4 5 6]]]

[1 2 3 4 5 6]

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

[1 2 3 4 5]


# numpy arithmatic operations

In [81]:
#addition
import numpy as np
var1=np.array([1,2,3,4,5])
var2=np.array([6,7,8,9,10])
print(var1+var2)

[ 7  9 11 13 15]


In [82]:
#subtraction
import numpy as np
var1=np.array([10,11,12,14,15])
var2=np.array([1,2,3,4,5])
print(var1-var2)

[ 9  9  9 10 10]


In [83]:
#multiplication
import numpy as np
var1=np.array([10,11,12,13,14])
var2=np.array([1,2,3,4,5])
print(var1*var2)

[10 22 36 52 70]


In [84]:
#division
import numpy as np
var1=np.array([12,15,18,21,24])
var2=np.array([3,3,3,3,3])
print(var1/var2)

[4. 5. 6. 7. 8.]


In [85]:
#modulus
import numpy as np
var1=np.array([12,15,18,21,24])
var2=np.array([2,3,2,3,2])
print(var1%var2)

[0 0 0 0 0]


In [86]:
#power
var1=np.array([1,2,3,4,5])
var2=np.array([10,11,12,13,14])
print(var2**var1)

[    10    121   1728  28561 537824]


# using functions perform the arithmatic operations

In [89]:
var1=np.array([5,10,15,20])
var2=np.array([1,1,1,1])
varadd=np.add(var1,var2)
print(varadd)
print()
varsub=np.subtract(var1,var2)
print(varsub)
print()
varmul=np.multiply(var1,var2)
print(varmul)
print()
vardiv=np.divide(var1,var2)
print(vardiv)
print()
varmod=np.mod(var1,var2)
print(varmod)
print()
varpow=np.power(var1,var2)
print(varpow)
print()
varreciprocal=np.reciprocal(var1)
print(varreciprocal)

[ 6 11 16 21]

[ 4  9 14 19]

[ 5 10 15 20]

[ 5. 10. 15. 20.]

[0 0 0 0]

[ 5 10 15 20]

[0 0 0 0]


# for 2d arrays

In [90]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
var2=np.array([[2,3,4,5],[6,7,8,9]])
print(var1+var2)

[[ 3  5  7  9]
 [11 13 15 17]]


# some more basic arithmatic functions

In [91]:
#max
import numpy as np
var=np.array([1,2,3,4,5,6,7])
print(np.max(var))
print()
#min
print(np.min(var))
print()
#argmax - determine pos of  max
print(np.argmax(var))
print()
#argmin - determinine pos of min
print(np.argmin(var))
print()
#sqrt
print(np.sqrt(var))
print()
#sin
print(np.sin(var))
print()
#cos
print(np.cos(var))
print()
#cumsum
print(np.cumsum(var))


7

1

6

0

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225]

[ 1  3  6 10 15 21 28]


# indexing in numpy arrays

# 1d arrays

In [93]:
import numpy as np
arr=np.array([1,2,3,4])
#to access first element
print(arr[0])
#to access second element
print(arr[1])
#to access third and fourth element by sum
print(arr[2]+arr[3])

1
2
7


# 2d arrays

In [98]:
import numpy as np
var=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element 1st row :",var[0,1])
print("5th element 2nd row :",var[1:4])

2nd element 1st row : 2
5th element 2nd row : [[ 6  7  8  9 10]]


# 3d arrays

In [107]:
import numpy as np
var=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("5th element on 2nd row :",var[0,1,2])
print("5th element on 2nd row :",var[1,1,2])
print()
var1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(var1[1,1,2])


5th element on 2nd row : 6
5th element on 2nd row : 12

12


# -ve indexing

In [106]:
var=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(var[1,-1])
print(var[0,-3])

10
3
